Repository openedx/credentials, pull requests merged in 2023-10, with the labels that each got.

#1912 chore: update Dockerfile to reduce the image size
  Dockerfile
Labels: open-source-contribution, waiting for eng review, needs maintainer attention

#2203 docs: fixed numbered list
  docs/verifiable_credentials/quickstart.rst
Labels: open-source-contribution, waiting for eng review

#2138 feat: upgraded to node v18, added .nvmrc and updated workflows
  .github/workflows/ci.yml
  .nvmrc
  Dockerfile
  package-lock.json
Labels: needs maintainer attention

#2220 feat(vc): backport missing migration for Verifiable Credentials app to palm
  credentials/apps/verifiable_credentials/migrations/0002_alter_issuanceline_subject_id.py
Labels: open-source-contribution
