Repository openedx/credentials, pull requests merged in 2023-09, with the labels that each got.

#2170 chore: upgrade Django to 3.2.21
  requirements/all.txt
  requirements/base.txt
  requirements/dev.txt
  requirements/django.txt
  requirements/production.txt
  requirements/translations.txt
Labels: open-source-contribution, waiting for eng review

#2153 feat: use `atlas` in `make pull_translations`
  Dockerfile
  Makefile
  requirements/all.txt
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/production.txt
  requirements/test.txt
Labels: open-source-contribution

#2142 fix: adding django42 support.
  .github/workflows/ci.yml
  credentials/apps/api/urls.py
  credentials/apps/api/v2/urls.py
  credentials/apps/core/__init__.py
  credentials/apps/core/admin.py
  credentials/apps/credentials/__init__.py
  credentials/apps/credentials/rest_api/urls.py
  credentials/apps/credentials/rest_api/v1/urls.py
  credentials/apps/credentials/urls.py
  credentials/apps/edx_django_extensions/tests/test_views.py
  credentials/apps/edx_django_extensions/urls.py
  credentials/apps/records/rest_api/urls.py
  credentials/apps/records/urls.py
  credentials/apps/verifiable_credentials/rest_api/urls.py
  credentials/apps/verifiable_credentials/urls.py
  credentials/settings/test.py
  credentials/urls.py
  tox.ini
Labels: waiting on author
