Repository openedx/credentials, pull requests merged in 2025-02, with the labels that each got.

#2695 chore: update Django to 4.2.19 for Sumac - Security Patch
  requirements/all.txt
  requirements/base.txt
  requirements/dev.txt
  requirements/django.txt
  requirements/production.txt
  requirements/translations.txt
Labels: open-source-contribution, needs maintainer attention

#2674 feat: [FC-0065] course credentials as verifiable credentials
  credentials/apps/verifiable_credentials/composition/schemas.py
  credentials/apps/verifiable_credentials/composition/tests/test_open_badges.py
  credentials/apps/verifiable_credentials/composition/tests/test_schemas.py
  credentials/apps/verifiable_credentials/conftest.py
  credentials/apps/verifiable_credentials/constants.py
  credentials/apps/verifiable_credentials/issuance/models.py
  credentials/apps/verifiable_credentials/rest_api/v1/tests/test_views.py
  credentials/apps/verifiable_credentials/rest_api/v1/urls.py
  credentials/apps/verifiable_credentials/rest_api/v1/views.py
  credentials/apps/verifiable_credentials/storages/learner_credential_wallet.py
  credentials/apps/verifiable_credentials/tests/test_utils.py
  credentials/apps/verifiable_credentials/utils.py
  credentials/conf/locale/eo/LC_MESSAGES/django.mo
  credentials/conf/locale/eo/LC_MESSAGES/django.po
  credentials/conf/locale/eo/LC_MESSAGES/djangojs.po
  credentials/conf/locale/rtl/LC_MESSAGES/django.mo
  credentials/conf/locale/rtl/LC_MESSAGES/django.po
  credentials/conf/locale/rtl/LC_MESSAGES/djangojs.po
  docs/verifiable_credentials/components.rst
  docs/verifiable_credentials/usage.rst
Labels: open-source-contribution, FC

#2675 feat: [FC-0065] add Accredible integration
  .annotation_safe_list.yml
  credentials/apps/badges/accredible/api_client.py
  credentials/apps/badges/accredible/data.py
  credentials/apps/badges/accredible/exceptions.py
  credentials/apps/badges/accredible/utils.py
  credentials/apps/badges/admin.py
  credentials/apps/badges/base_api_client.py
  credentials/apps/badges/credly/api_client.py
  credentials/apps/badges/exceptions.py
  credentials/apps/badges/issuers.py
  credentials/apps/badges/management/commands/sync_accredible_groups.py
  credentials/apps/badges/migrations/0002_accredibleapiconfig_accrediblebadge_and_more.py
  credentials/apps/badges/models.py
  credentials/apps/badges/signals/handlers.py
  credentials/apps/badges/signals/signals.py
  credentials/apps/badges/tests/accredible/__init__.py
  credentials/apps/badges/tests/accredible/test_api_client.py
  credentials/apps/badges/tests/accredible/test_utils.py
  credentials/apps/badges/tests/test_admin_forms.py
  credentials/apps/badges/tests/test_issuers.py
  credentials/apps/badges/tests/test_management_commands.py
  credentials/apps/badges/tests/test_models.py
  credentials/apps/badges/tests/test_signals.py
  credentials/apps/credentials/migrations/0032_alter_usercredential_credential_content_type.py
  credentials/apps/credentials/models.py
  credentials/apps/credentials/tests/test_api.py
  credentials/conf/locale/eo/LC_MESSAGES/django.mo
  credentials/conf/locale/eo/LC_MESSAGES/django.po
  credentials/conf/locale/rtl/LC_MESSAGES/django.mo
  credentials/conf/locale/rtl/LC_MESSAGES/django.po
  credentials/settings/base.py
  docs/_static/images/badges/badges-admin-groups-sync.png
  docs/_static/images/badges/badges-admin.png
  docs/badges/configuration/accredible.rst
  docs/badges/configuration/credly.rst
  docs/badges/configuration/index.rst
  docs/badges/index.rst
  docs/badges/processing.rst
  docs/badges/quickstart.rst
  docs/badges/settings.rst
Labels: open-source-contribution, FC

#2694 chore: update paragon 23
  credentials/apps/credentials_theme_openedx/static/sass/_print-rendering.scss
  credentials/static/sass/_components.scss
  credentials/static/sass/_config.scss
  credentials/static/sass/_layouts.scss
  credentials/static/sass/_lib.scss
  package-lock.json
  package.json
Labels: needs maintainer attention

#2706 refactor: update deprecated requestmetric middleware
  credentials/settings/base.py
Labels: open-source-contribution
